{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "prometheus-dnssec-exporter.fullname" . }}
  labels:
    {{- include "prometheus-dnssec-exporter.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus-dnssec-exporter.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.podMonitor.interval }}
      scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
{{- end }}
